# Generated by Django 2.2b1 on 2021-06-29 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Danie',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_dania', models.CharField(max_length=30)),
                ('zdjecie', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_skladnika', models.CharField(max_length=30)),
                ('wielkosc_porcji_skladnika', models.FloatField()),
                ('energia_skladnika_kcal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Typ_dania',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_typu_dania', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zestaw',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_zestawu', models.CharField(max_length=30)),
                ('data_zestawu', models.DateTimeField()),
                ('czy_widoczny', models.BooleanField(default=False)),
                ('cena_zestawu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zestaw_dan',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('danie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Danie')),
                ('zestaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Zestaw')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('data_zamowienia', models.DateTimeField()),
                ('czy_potwierdzone', models.BooleanField(default=False)),
                ('komentarz_zamowienia', models.TextField(blank=True, null=True)),
                ('zamawiajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik_dania',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('danie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Danie')),
                ('skladnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Skladnik')),
            ],
        ),
        migrations.CreateModel(
            name='Pozycja_zamowienia',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Zamowienie')),
                ('Zestaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Zestaw')),
            ],
        ),
        migrations.AddField(
            model_name='danie',
            name='typ_dania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Typ_dania'),
        ),
    ]
