# Generated by Django 2.2b1 on 2021-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danie',
            name='komentarz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
