# Generated by Django 2.2b1 on 2021-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0002_danie_komentarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zestaw',
            name='data_zestawu',
            field=models.DateField(),
        ),
    ]
