# Generated by Django 2.2b1 on 2021-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0007_auto_20210701_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestaw_dan',
            name='ilosc_zestawow',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
