# Generated by Django 2.2b1 on 2021-07-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0010_auto_20210702_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='Zestaw',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catering_przedszkole.Zestaw'),
        ),
        migrations.DeleteModel(
            name='Pozycja_zamowienia',
        ),
    ]
