# Generated by Django 2.2b1 on 2021-07-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0011_auto_20210702_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zamowienie',
            old_name='Zestaw',
            new_name='zestaw',
        ),
    ]
