# Generated by Django 2.2b1 on 2021-07-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0015_auto_20210707_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danie',
            name='zdjecie',
            field=models.ImageField(blank=True, default='brak_zdjecia.png', upload_to='image'),
        ),
    ]
