# Generated by Django 2.2b1 on 2021-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0018_auto_20210721_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danie',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
