# Generated by Django 2.2b1 on 2021-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0019_auto_20210721_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danie',
            name='nazwa_dania',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='nazwa_skladnika',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='typ_dania',
            name='nazwa_typu_dania',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='zestaw',
            name='nazwa_zestawu',
            field=models.CharField(max_length=100),
        ),
    ]
