# Generated by Django 2.2b1 on 2021-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0023_uzytkownik_waiting_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='czy_oplacone',
            field=models.BooleanField(default=False),
        ),
    ]
