# Generated by Django 2.2b1 on 2021-09-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0024_zamowienie_czy_oplacone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='do_zaplaty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
