# Generated by Django 2.2b1 on 2021-10-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0025_zamowienie_do_zaplaty'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='address',
            field=models.CharField(default=' ', max_length=80),
        ),
    ]
