# Generated by Django 2.2b1 on 2021-12-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering_przedszkole', '0026_uzytkownik_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='czas_dostawy',
            field=models.TimeField(default='08:00'),
        ),
    ]
